#include "Host.h"
#include <algorithm>
#include <cstring>
#include <iostream>
#include <fcntl.h>
#include <unistd.h>
namespace studio {
HostStorage::HostStorage(fs::path root):root_(fs::absolute(root)){fs::create_directories(root_);root_=fs::canonical(root_);for(auto n:{"Projects","Sounds/Factory","Sounds/My Sounds","Samples/Factory","Samples/My Samples","Sound Paks","Recordings","Imports","Exports","System","Recently Deleted"})fs::create_directories(root_/n);}
fs::path HostStorage::resolve(const std::string&s)const{fs::path p(s);if(p.empty()||p.is_absolute())return {};for(const auto&part:p)if(part=="..")return {};auto candidate=root_/p;std::error_code ec;auto real=fs::weakly_canonical(candidate,ec);if(ec)return {};auto r=root_.begin(),v=real.begin();for(;r!=root_.end();++r,++v)if(v==real.end()||*r!=*v)return {};if(real==root_)return {};return real;}
bool HostStorage::read(const char*p,uint8_t*b,size_t cap,size_t&n){n=0;auto f=resolve(p);if(f.empty())return false;std::ifstream in(f,std::ios::binary|std::ios::ate);if(!in)return false;auto size=in.tellg();if(size<0||uint64_t(size)>cap)return false;n=size_t(size);in.seekg(0);in.read(reinterpret_cast<char*>(b),n);if(!in)return false;touch(p);return true;}
bool HostStorage::atomicWrite(const char*p,const uint8_t*b,size_t n){auto f=resolve(p);if(f.empty())return false;std::error_code ec;fs::create_directories(f.parent_path(),ec);if(ec)return false;std::string pattern=f.string()+".tmp.XXXXXX";std::vector<char> name(pattern.begin(),pattern.end());name.push_back(0);int fd=mkstemp(name.data());if(fd<0)return false;size_t done=0;while(done<n){auto wrote=::write(fd,b+done,n-done);if(wrote<=0)break;done+=size_t(wrote);}bool ok=done==n&&fsync(fd)==0;::close(fd);if(ok){fs::rename(name.data(),f,ec);ok=!ec;}if(!ok)fs::remove(name.data(),ec);else {int dir=open(f.parent_path().c_str(),O_RDONLY);if(dir>=0){fsync(dir);::close(dir);}touch(p);}return ok;}
std::vector<FileInfo> HostStorage::browse(const std::string&folder,const std::string&q)const{std::vector<FileInfo> out;auto f=folder.empty()?root_:resolve(folder);if(f.empty())return out;std::error_code ec;for(fs::directory_iterator it(f,ec),end;it!=end&&!ec;it.increment(ec)){auto name=it->path().filename().string();if(name=="System"||name.find(q)==std::string::npos||it->is_symlink())continue;bool dir=it->is_directory();out.push_back({fs::relative(it->path(),root_).string(),dir?0:it->file_size(),dir});}std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.path<b.path;});return out;}
bool HostStorage::copy(const std::string&a,const std::string&b){auto x=resolve(a),y=resolve(b);if(x.empty()||y.empty())return false;std::error_code ec;return fs::copy_file(x,y,fs::copy_options::none,ec)&&!ec;}
bool HostStorage::move(const std::string&a,const std::string&b){auto x=resolve(a),y=resolve(b);if(x.empty()||y.empty()||fs::exists(y))return false;std::error_code ec;fs::rename(x,y,ec);return !ec;}
bool HostStorage::trash(const std::string&a,std::string&dest){auto p=resolve(a);if(p.empty()||!fs::is_regular_file(p))return false;for(unsigned i=0;i<100000;++i){dest="Recently Deleted/"+std::to_string(i)+"-"+p.filename().string();if(!fs::exists(resolve(dest)))return move(a,dest);}return false;}
bool HostStorage::restore(const std::string&a,const std::string&b){if(a.rfind("Recently Deleted/",0)!=0)return false;return move(a,b);}
uint64_t HostStorage::freeBytes()const{std::error_code ec;auto s=fs::space(root_,ec);return ec?0:s.available;}
void HostStorage::touch(const std::string&p){recent_.erase(std::remove(recent_.begin(),recent_.end(),p),recent_.end());recent_.insert(recent_.begin(),p);if(recent_.size()>16)recent_.resize(16);}
namespace {uint16_t u16(const uint8_t*p){return uint16_t(p[0])|uint16_t(p[1])<<8;}uint32_t u32(const uint8_t*p){return uint32_t(u16(p))|uint32_t(u16(p+2))<<16;}}
bool HostAssets::addWav(uint32_t id,const fs::path&path,StemAsset*meta){if(!id)return false;Wav w;w.file.open(path,std::ios::binary|std::ios::ate);if(!w.file)return false;uint64_t fileSize=uint64_t(w.file.tellg());w.file.seekg(0);uint8_t h[16]{};if(!w.file.read(reinterpret_cast<char*>(h),12)||std::memcmp(h,"RIFF",4)||std::memcmp(h+8,"WAVE",4)||uint64_t(u32(h+4))+8!=fileSize)return false;bool fmt=false,data=false;uint32_t bytes=0;uint64_t pos=12;
 while(pos+8<=fileSize){w.file.seekg(pos);if(!w.file.read(reinterpret_cast<char*>(h),8))return false;uint32_t n=u32(h+4);if(uint64_t(n)>fileSize-pos-8)return false;if(!std::memcmp(h,"fmt ",4)){if(fmt||n<16)return false;w.file.read(reinterpret_cast<char*>(h),16);if(u16(h)!=1)return false;w.channels=u16(h+2);w.rate=u32(h+4);w.bits=u16(h+14);if(w.channels!=2||w.bits!=16||u16(h+12)!=4||u32(h+8)!=w.rate*4)return false;fmt=true;}else if(!std::memcmp(h,"data",4)){if(data)return false;w.offset=pos+8;bytes=n;data=true;}pos+=8+uint64_t(n)+(n&1);}
 if(!fmt||!data||!bytes||bytes%4||w.rate!=SampleRate)return false;w.frames=bytes/4;if(meta){meta->asset=id;meta->frames=w.frames;meta->sampleRate=w.rate;meta->channels=w.channels;meta->bits=w.bits;meta->alignmentOffset=0;std::strncpy(meta->file,path.filename().c_str(),sizeof(meta->file)-1);}wavs_[id]=std::move(w);return true;}
void HostAssets::addMemory(uint32_t id,std::vector<Stereo>x){memory_[id]=std::move(x);}
uint64_t HostAssets::length(uint32_t id)const{auto m=memory_.find(id);if(m!=memory_.end())return m->second.size();auto w=wavs_.find(id);return w==wavs_.end()?0:w->second.frames;}
bool HostAssets::frame(uint32_t id,uint64_t pos,Stereo&out){out={};auto m=memory_.find(id);if(m!=memory_.end()){if(pos>=m->second.size())return false;out=m->second[pos];return true;}auto it=wavs_.find(id);if(it==wavs_.end()||pos>=it->second.frames)return false;auto&w=it->second;uint64_t start=(pos/1024)*1024;if(w.cacheStart!=start){w.file.clear();w.file.seekg(w.offset+start*4);size_t n=size_t(std::min(uint64_t(4096),(w.frames-start)*4));w.file.read(reinterpret_cast<char*>(w.cache.data()),n);w.cacheBytes=size_t(w.file.gcount());w.cacheStart=start;}size_t i=size_t(pos-start)*4;if(i+4>w.cacheBytes)return false;out={int16_t(u16(w.cache.data()+i))/32768.f,int16_t(u16(w.cache.data()+i+2))/32768.f};return true;}
bool HostAssets::preparedFolder(const fs::path&folder,StemSet&s,std::string&error){HostAssets staged;StemSet candidate;candidate.id=1;std::strncpy(candidate.title,folder.filename().c_str(),sizeof candidate.title-1);for(unsigned i=0;i<4;++i)if(!staged.addWav(100+i,folder/StemFiles[i],&candidate.stems[i])){error=std::string("Invalid or missing ")+StemFiles[i];return false;}if(auto e=validate(candidate,staged)){error=e;return false;}for(auto&entry:staged.wavs_)wavs_[entry.first]=std::move(entry.second);s=candidate;return true;}
void TextDisplay::clear(uint32_t){std::cout<<"\n";}void TextDisplay::label(int,int,const char*s,uint32_t){std::cout<<s<<"\n";}
}
