#include "Host.h"
#include "studio/App.h"
#include "studio/Persistence.h"
#include "studio/Ui.h"
#include "studio/AudioQueue.h"
#include "studio/Journal.h"
#include "studio/Controls.h"
#include "studio/Presets.h"
#include <iostream>
#include <cstring>
#include <stdexcept>
#include <limits>
#include <unistd.h>
using namespace studio;
static unsigned checks=0;
#define CHECK(x) do{++checks;if(!(x))throw std::runtime_error(std::string(__func__)+":"+std::to_string(__LINE__)+" " #x);}while(0)
static bool near(float a,float b,float tol=.0001f){return std::fabs(a-b)<tol;}
static StemSet fixture(HostAssets&a,unsigned frames=1000){StemSet s;s.id=1;for(unsigned i=0;i<4;++i){a.addMemory(100+i,std::vector<Stereo>(frames,Stereo{.1f*float(i+1),.1f*float(i+1)}));auto&m=s.stems[i];m.asset=100+i;m.sampleRate=44100;m.frames=frames;m.channels=2;m.bits=16;std::strcpy(m.file,StemFiles[i]);}return s;}
void transport(){Transport t;t.setBpm(120);t.record(1);for(int i=0;i<88200;++i)t.advance();CHECK(t.recording);CHECK(!t.counting());CHECK(t.ticks()==0);for(int i=0;i<22050;++i)t.advance();CHECK(t.ticks()==96);t.stop();CHECK(!t.recording&&t.frames==0);t.tap(0);t.tap(500);CHECK(near(t.bpm,120));t.setBpm(NAN);CHECK(near(t.bpm,120));t.external=true;t.play();for(int i=0;i<24;++i)t.midiClock();CHECK(t.ticks()==96);}
void stems(){HostAssets a;auto s=fixture(a);CHECK(!validate(s,a));StemPlayer p;CHECK(p.load(s,a));std::array<Stereo,4> out;for(int i=0;i<1000;++i){CHECK(p.read(a,out));for(int j=0;j<4;++j)CHECK(near(out[j].l,.1f*(j+1)));}CHECK(!p.read(a,out));CHECK(p.position()==1000);auto bad=s;bad.stems[2].frames--;CHECK(validate(bad,a));bad=s;bad.stems[1].sampleRate=48000;CHECK(validate(bad,a));bad=s;bad.stems[1].alignmentOffset=1;CHECK(validate(bad,a));bad=s;std::strcpy(bad.stems[1].file,"other.wav");CHECK(validate(bad,a));bad=s;bad.stems[3].asset=100;CHECK(validate(bad,a));PreparedStemEngine e;e.submit(s,a);CHECK(e.status().stage==ImportStage::Ready);e.cancel();CHECK(!e.prepared(s));}
void tails(){StudioDsp dsp;Fx f;f.enabled=true;f.effect=Effect::DigitalDelay;f.timeSeconds=10.f/SampleRate;f.intensity=1;f.wet={1,1};f.feedback={.5f,.5f};f.width={1,1};f.drive={0,0};dsp.process({1,1},f);f.enabled=false;float energy=0;for(int i=0;i<100;++i){auto x=dsp.process({},f);energy+=x.l*x.l;}CHECK(energy>.1f);Mapping m{0,1,Curve::Square};CHECK(near(m.at(.5f),.25f));CHECK(near(m.at(-1),0));CHECK(near(m.at(2),1));}
void integratedAudio(){HostAssets a;auto s=fixture(a,100);AudioEngine e(a);Project p;Settings cfg;CHECK(e.loadStems(s));p.master=1;for(auto&l:p.dub)l.volume=0;p.dub[0].fx.enabled=true;p.dub[0].fx.intensity=1;p.dub[0].fx.timeSeconds=2.f/SampleRate;e.transport.play();float wet=0;for(int i=0;i<20;++i)wet+=std::fabs(e.process(p,Mode::Dub,cfg).main.l);CHECK(wet>0);e.stop();a.addMemory(1,std::vector<Stereo>(20,Stereo{.2f,.2f}));AudioEngine preview(a);CHECK(preview.previewAsset(1));auto f=preview.process(p,Mode::Dub,cfg);CHECK(near(f.main.l,0));CHECK(f.headphones.l>0);Master m;auto limited=m.process({2,1},1);CHECK(near(limited.l,.98f));CHECK(near(limited.r,.49f));CHECK(m.meters.clipping);CHECK(near(m.process({NAN,1},1).l,0));OneShot shot;CHECK(shot.trigger(1,a,Retrigger::Unconfigured));CHECK(!shot.trigger(1,a,Retrigger::Unconfigured));for(int i=0;i<20;++i)CHECK(near(shot.process(a).l,.2f));CHECK(!shot.active());}
void app(){HostAssets assets;auto set=fixture(assets);AudioEngine e(assets);App a(e);a.mode(Mode::Dub);a.control({Control::Top,0});CHECK(a.project.dub[0].fx.enabled);a.control({Control::EncoderTurn,0,22});CHECK(near(a.project.dub[0].fx.intensity,.72f));a.control({Control::Top,0});CHECK(!a.project.dub[0].fx.enabled);CHECK(near(a.project.dub[0].fx.intensity,.72f));a.control({Control::EncoderClick,0});a.control({Control::EncoderTurn,0,2});a.control({Control::EncoderClick,0});CHECK(a.project.dub[0].fx.effect==Effect::RoomReverb);CHECK(a.undo());CHECK(a.project.dub[0].fx.effect==Effect::DubEcho);CHECK(a.redo());a.control({Control::Fader,9,1});a.mode(Mode::Jam);a.control({Control::Top,1});CHECK(!a.project.tracks[1].armed);a.settings.jamPhysicalMapping=true;a.control({Control::Top,1});CHECK(a.project.tracks[1].armed);a.openFiles(FileContext::Action::AssignSlot,2);CHECK(a.chooseAsset(100,SoundKind::Sample));CHECK(a.project.slots[2]==100);CHECK(a.session.mode==Mode::Jam);PreparedStemEngine engine;engine.submit(set,assets);CHECK(a.openDub(engine));CHECK(a.project.stemSet==1);}
void jam(){CHECK(scaleNote(61,0,Scale::Major,true)==60);CHECK(scaleNote(61,0,Scale::Chromatic,true)==61);Project p;JamEngine j;j.note(p,3,60,1,true,0);float energy=0;for(int i=0;i<200;++i)energy+=std::fabs(j.process(p).l);CHECK(energy>0);j.note(p,3,60,0,false,0);for(int i=0;i<10000;++i)j.process(p);CHECK(near(j.process(p).l,0));CHECK(j.startLoop(p,2));j.note(p,2,64,.8f,true,24);j.note(p,2,64,0,false,48);j.finishLoop(p,2,200);CHECK(p.tracks[2].loop.count==2);CHECK(p.tracks[2].loop.lengthTicks==384);CHECK(p.tracks[2].loop.playing);p.tracks[0].pattern.steps[0]={true,60,.8f,.5f};j.sequence(p,0);}
void persistence(){Project p;p.dub[1].fx.intensity=.72f;p.tracks[3].pattern.steps[7]={true,82,.4f,.3f};std::array<uint8_t,ProjectBytes>b{};auto n=encodeProject(p,b.data(),b.size());CHECK(n>0);Project q;CHECK(decodeProject(b.data(),n,q));CHECK(near(q.dub[1].fx.intensity,.72f));CHECK(q.tracks[3].pattern.steps[7].note==82);CHECK(!decodeProject(b.data(),n-1,q));b[100]^=1;CHECK(!decodeProject(b.data(),n,q));CHECK(!encodeProject(p,b.data(),30));HostStorage s(fs::temp_directory_path()/("studio-test-"+std::to_string(getpid())));CHECK(saveProject(s,"Projects/test.studio",p));CHECK(loadProject(s,"Projects/test.studio",q));CHECK(s.resolve("../escape").empty());CHECK(s.resolve("/etc/passwd").empty());CHECK(s.copy("Projects/test.studio","Projects/copy.studio"));CHECK(!s.copy("Projects/test.studio","Projects/copy.studio"));CHECK(s.browse("Projects","copy").size()==1);std::string trash;CHECK(s.trash("Projects/copy.studio",trash));CHECK(s.restore(trash,"Projects/restored.studio"));HostAssets assets;AudioEngine audio(assets);App app(audio);app.edit();CHECK(!app.autosave(s,1));CHECK(app.autosave(s,30000));CHECK(app.recover(s));fs::remove_all(s.resolve("Projects").parent_path());}
struct Display:IDisplay{std::string text;void clear(uint32_t)override{text.clear();}void label(int x,int y,const char*s,uint32_t)override{text+=std::to_string(x)+","+std::to_string(y)+s;}};
void themesQueue(){HostAssets a;AudioEngine e(a);App app(e);Display d;render(app,d);auto baseline=d.text;for(int i=0;i<8;++i){app.project.theme=Theme(i);render(app,d);CHECK(d.text==baseline);}AudioQueue q;for(int i=0;i<3;++i){auto b=q.beginWrite();CHECK(b);(*b)[0].main.l=float(i);q.commit();}CHECK(!q.beginWrite());for(int i=0;i<3;++i){auto b=q.beginRead();CHECK(b);CHECK((*b)[0].main.l==i);q.release();}CHECK(!q.beginRead());CHECK(q.underruns==1);}
struct Raw:IRawStorage {std::map<std::string,std::vector<uint8_t>> files;bool fail=false;
 bool readBlob(const char*p,uint8_t*b,size_t cap,size_t&n)override{auto i=files.find(p);if(i==files.end()||i->second.size()>cap)return false;n=i->second.size();std::memcpy(b,i->second.data(),n);return true;}
 bool writeBlob(const char*p,const uint8_t*b,size_t n)override{files[p]={b,b+(fail?n/2:n)};return !fail;}};
void journal(){Raw raw;JournalStorage s(raw);Project p,q;CHECK(saveProject(s,"Projects/session",p));p.bpm=120;CHECK(saveProject(s,"Projects/session",p));CHECK(loadProject(s,"Projects/session",q));CHECK(q.bpm==120);raw.fail=true;p.bpm=140;CHECK(!saveProject(s,"Projects/session",p));CHECK(loadProject(s,"Projects/session",q));CHECK(q.bpm==120);raw.fail=false;CHECK(saveProject(s,"Projects/session",p));CHECK(loadProject(s,"Projects/session",q));CHECK(q.bpm==140);}
void controlsAndRecording(){DebouncedButton b;CHECK(!b.press(true,0));CHECK(!b.press(false,3));CHECK(!b.press(true,5));CHECK(b.press(true,17));CHECK(!b.press(true,30));FaderCalibration f;CHECK(near(f.normalized(1023),1));CHECK(near(f.normalized(-10),0));HostAssets assets;AudioEngine e(assets);App a(e);a.mode(Mode::Jam);a.project.bpm=120;a.project.countInBars=1;a.control({Control::Record});for(int i=0;i<88201;++i)e.process(a.project,Mode::Jam,a.settings);CHECK(a.project.tracks[0].loop.recording);a.note(60,.8f,true);for(int i=0;i<1000;++i)e.process(a.project,Mode::Jam,a.settings);a.note(60,0,false);a.control({Control::Record});CHECK(a.project.tracks[0].loop.playing);CHECK(a.project.tracks[0].loop.count==2);CHECK(!a.project.tracks[0].loop.recording);CHECK(keyboardNote(a.project,23)==71);CHECK(keyboardNote(a.project,24)==-1);Raw raw;JournalStorage storage(raw);Sound sound;sound.kind=SoundKind::Saw;CHECK(saveSound(storage,"Sounds/test",sound));Sound loaded;CHECK(loadSound(storage,"Sounds/test",loaded));CHECK(loaded.kind==SoundKind::Saw);Fx fx;CHECK(!loadFx(storage,"Sounds/test",fx));}
void wav(){auto root=fs::temp_directory_path()/("studio-wave-"+std::to_string(getpid()));HostStorage storage(root);std::vector<uint8_t> data(44+16);auto put16=[&](size_t i,uint16_t v){data[i]=uint8_t(v);data[i+1]=uint8_t(v>>8);};auto put32=[&](size_t i,uint32_t v){put16(i,v);put16(i+2,v>>16);};std::memcpy(data.data(),"RIFF",4);put32(4,52);std::memcpy(data.data()+8,"WAVEfmt ",8);put32(16,16);put16(20,1);put16(22,2);put32(24,44100);put32(28,176400);put16(32,4);put16(34,16);std::memcpy(data.data()+36,"data",4);put32(40,16);put16(44,16384);put16(46,uint16_t(-16384));CHECK(storage.atomicWrite("Samples/test.wav",data.data(),data.size()));HostAssets a;StemAsset m;CHECK(a.addWav(1,storage.resolve("Samples/test.wav"),&m));CHECK(m.frames==4);Stereo out;CHECK(a.frame(1,0,out));CHECK(near(out.l,.5f));CHECK(near(out.r,-.5f));CHECK(!a.frame(1,4,out));data.resize(50);CHECK(storage.atomicWrite("Samples/bad.wav",data.data(),data.size()));CHECK(!a.addWav(2,storage.resolve("Samples/bad.wav")));fs::remove_all(root);}
int main(){try{transport();stems();tails();integratedAudio();app();jam();persistence();themesQueue();journal();controlsAndRecording();wav();std::cout<<"PASS "<<checks<<" checks in 11 test groups\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
