#include "Jam.h"
#include <algorithm>
namespace studio {
int scaleNote(int n,uint8_t key,Scale s,bool lock){n=std::max(0,std::min(127,n));if(!lock)return n;constexpr uint16_t masks[]={0xAB5,0x5AD,0x295,0x4E9,0x6AD,0x6B5,0xFFF};auto valid=[&](int v){return v>=0&&v<=127&&(masks[unsigned(s)<7?unsigned(s):6]&(1<<((v-int(key)+120)%12)));};for(int d=0;d<12;++d){if(valid(n-d))return n-d;if(valid(n+d))return n+d;}return n;}
void JamEngine::note(Project&p,unsigned lane,uint8_t n,float velocity,bool on,uint64_t tick,bool capture){if(lane>=4||n>127)return;auto&t=p.tracks[lane];n=uint8_t(scaleNote(n,p.key,p.scale,p.scaleLock));if(capture&&t.loop.recording&&t.loop.count<t.loop.events.size())t.loop.events[t.loop.count++]={uint32_t(tick-loopStart_[lane]),n,unit(velocity),on};
 auto&vs=voices_[lane];if(!on){for(auto&v:vs)if(v.note==n)v.held=false;return;}Voice* target=&vs[0];for(auto&v:vs)if(!v.held&&v.env<.001f){target=&v;break;}*target={0,0,unit(velocity),n,true};}
void JamEngine::stop(){voices_={};lastTick_=UINT64_MAX;}
bool JamEngine::startLoop(Project&p,unsigned i,uint64_t tick){if(i>=4)return false;loopStart_[i]=tick;auto&l=p.tracks[i].loop;l.count=0;l.recording=true;l.playing=false;return true;}
void JamEngine::finishLoop(Project&p,unsigned i,uint32_t ticks){if(i>=4)return;auto&l=p.tracks[i].loop;l.lengthTicks=std::max<uint32_t>(384,((uint32_t(ticks-loopStart_[i])+383)/384)*384);for(unsigned n=0;n<l.count;++n)l.events[n].tick%=l.lengthTicks;l.recording=false;l.playing=true;}
void JamEngine::sequence(Project&p,uint64_t tick){if(tick==lastTick_)return;lastTick_=tick;for(unsigned i=0;i<4;++i){auto&t=p.tracks[i];unsigned step=unsigned(tick/24)%16;const auto&s=t.pattern.steps[step];if(tick%24==0&&s.on)note(p,i,s.note,s.velocity,true,tick,false);if(s.on&&tick%24==unsigned(std::max(1.f,std::min(23.f,s.gate*24))))note(p,i,s.note,0,false,tick,false);auto&l=t.loop;if(l.playing&&l.lengthTicks)for(unsigned j=0;j<l.count;++j){const auto&e=l.events[j];if(tick%l.lengthTicks==e.tick)note(p,i,e.note,e.velocity,e.on,tick,false);}}}
Stereo JamEngine::process(const Project&p,IAudioAssets*assets){float out=0;for(unsigned i=0;i<4;++i){const auto&s=p.tracks[i].sound;for(auto&v:voices_[i]){float attack=std::max(.001f,s.attack),release=std::max(.005f,s.release);if(v.held)v.env=std::min(1.f,v.env+1/(attack*SampleRate));else v.env=std::max(0.f,v.env-1/(release*SampleRate));float hz=440*std::pow(2.f,(int(v.note)-69)/12.f);v.phase+=hz/SampleRate;if(v.phase>=1)v.phase-=1;float wave=std::sin(v.phase*6.2831853f);if(s.kind==SoundKind::Saw)wave=(2*v.phase-1)*(.2f+.8f*s.macro);if(s.kind==SoundKind::Drum){noise_=1664525*noise_+1013904223;wave=.5f*wave+.5f*(float(noise_>>8)/8388608-1);v.env*=.999f;v.held=false;}if(s.kind==SoundKind::Sample){Stereo sample{};if(assets&&assets->frame(s.asset,uint64_t(v.samplePosition),sample)){wave=(sample.l+sample.r)*.5f;v.samplePosition+=std::pow(2.,(int(v.note)-60)/12.);}else{wave=0;v.held=false;}}v.filtered+=std::max(.001f,unit(s.cutoff))*(wave-v.filtered);wave=v.filtered;out+=std::tanh(wave*(1+3*unit(s.drive)))*v.env*v.velocity*p.tracks[i].volume*.1f;}}return {out,out};}
}
